### ISSUE TITLE
interval_color_mapping

### ISSUE THREAD

**Issue by smk0033** [MAAP-Project/maap-documentation#236]
## EPIC Link
#230 

## Description
The tutorial https://docs.maap-project.org/en/latest/technical_tutorials/visualization/interval_color_mapping.html?highlight=interval%20color%20mapping is broken. We need to fix.

## Acceptance Criteria (Tasks):
- [ ] Fix the [notebook](https://github.com/MAAP-Project/maap-documentation/blob/d4ac397b9438c65c91100845241210c2418aa884/docs/source/technical_tutorials/visualization/interval_color_mapping.ipynb)

**Comment by sdradsb** [comment]
“issue with [‘features’] in 3rd cell” This issue is fixed by changing to a different collection, but this tutorial in the later cells are using the impact titiler. With reference to this [comment](https://github.com/NASA-IMPACT/active-maap-sprint/issues/548#issuecomment-1553729057), do you think [this](https://docs.maap-project.org/en/latest/technical_tutorials/visualization/interval_color_mapping.html?highlight=interval%20color%20mapping) tutorial can be removed?

Link to the PR: https://github.com/MAAP-Project/maap-documentation/pull/253

**Comment by wildintellect** [comment]
@sdradsb 
- Switch to using https://titiler.maap-project.org
- Switch to a different collection is fine, try https://stac-browser.maap-project.org/collections/NASA_JPL_global_agb_mean_2020

This is an important tutorial that we need to keep, it's the only one that shows custom coloring for tile services.
 
I'm going to highlight it for @emmalu also as it helps to understand the stac_ipyleaflet custom color feature request.
