### ISSUE TITLE
Align searching_edsc_gui to VEDA notebook guidelines

### ISSUE THREAD

**Issue by smk0033** [MAAP-Project/maap-documentation#287]
## EPIC
#263 

## Description
The [searching_edsc_gui](https://docs.maap-project.org/en/latest/technical_tutorials/search/searching_edsc_gui.html) notebook should be reviewed using the this [guidance](https://nasa-impact.github.io/veda-docs/example-notebooks/#contributing-to-veda) and includes the following components:
1. Style
2. Rendering Information
3. Notebook Sections

### Acceptance Criteria (Tasks):

- [ ] Style should be consistent with guidance provided
- [ ] Rendering information should be complete and accurate. If there is no author/date information available, use Git Blame and Git History.
- [ ] Ensure notebooks include the recommended standard sections

**Comment by jjfrench** [comment]
I guess the "Data Search" functionalities in the ADE are broken

**Comment by smk0033** [comment]
Yeah, they have been broken for a little while😅

**Comment by wildintellect** [comment]
You should work with Grace from JPL on this one.

**Comment by grallewellyn** [comment]
They worked for a brief period of time this year 😅
The cause of them stopping to work again is a bug I encountered when I was fixing the extension original in April/ May, and the bug just went away without me making changes to the code. I don't believe the bug is on our end. 

If anyone is interested/ has more insight: 

The first problem with edsc is that the dit earthdata search proxy isn't working, so I am using the ops earthdata search proxy which does work. The other problem which I believe is unrelated is a problem that I have seen before: 
Basically the event listener isn't being triggered when the user adds a dataset. I know it should be working because it's the same code that worked in the past, and if I do a postMessage somewhere else in the code, the event listener is triggered. 
I saw this error last on April 20th of this error, but then a week later the code started working again with no code changes on my part 

If I try changing the edsc_server to be https://ade.ops.maap-project.org:30052/search (instead of the dit one), then the print statement 'edsc url changed' is printed everytime I add or remove a collection. That print statement isn't in our edsc jupyter extension code, but I know something is being triggered to print 'edsc url changed' even though our event listener isn't being triggered 
The network requests when selecting a collection for https://ade.dit.maap-project.org:30052 look like https://cmr.earthdata.nasa.gov/search/granules.json while the requests for https://ade.ops.maap-project.org:30052/search look like https://cmr.maap-project.org/search/collections.json
Does anyone know what could have changed to have the event listener not be triggered anymore for edsc jupyter extension?
